spring:
  data:
    mongodb:
      uri: mongodb+srv://myAtlasDBUser:skmamun000@myatlasclusteredu.zmk3wd2.mongodb.net/?appName=myAtlasClusterEDU
      database: journaldb
      auto-index-xreation: true

server:
  port: 8080
  servlet:
    context-path: /journal